raw_data_dir: resources/raw_data
results_dir: results

build_analysis_inputs: true
run_association_tests: true

pyseer_repo_url: https://github.com/mgalardini/pyseer.git
pyseer_repo_dir: resources/pyseer

run_quast: true

run_panaroo_qc: true
panaroo_qc_graph_type: all
panaroo_qc_threads: 1

run_panaroo_pangenome: true
panaroo_clean_mode: strict
panaroo_alignment: core
panaroo_threads: 4

run_kmers: false #kmer-counting

kmer_min: 1
kmer_max: 3

association:
  phenotype_column: transformed_mic
  mash_sketch_size: 10000

  snp_gwas:
    min_af: 0.02
    max_af: 0.98
    max_dimensions: 1
    print_samples: false

  gwas_tests:
    snps:
      fixed_effects:
        mash: true
        phylogeny: true
      lmm:
        phylogeny: true
        genotype: true
    genes: false
    kmers: false

quast:
  reference: resources/quast/USA300_FPR3757.fasta
  annotation: resources/quast/USA300_FPR3757.gff3

antibiotics:
  #- oxacillin
  - levofloxacin
